// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: virtual_controls.sql

package db

import (
	"context"
)

const createVirtualControl = `-- name: CreateVirtualControl :one
INSERT INTO virtual_controls (topic, value, created_at, updated_at)
VALUES (?, ?, datetime(), datetime())
RETURNING topic, value, created_at, updated_at
`

type CreateVirtualControlParams struct {
	Topic string `json:"topic"`
	Value string `json:"value"`
}

func (q *Queries) CreateVirtualControl(ctx context.Context, arg CreateVirtualControlParams) (VirtualControl, error) {
	row := q.db.QueryRowContext(ctx, createVirtualControl, arg.Topic, arg.Value)
	var i VirtualControl
	err := row.Scan(
		&i.Topic,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVirtualControl = `-- name: DeleteVirtualControl :one
DELETE
FROM virtual_controls
WHERE topic = ?
RETURNING topic, value, created_at, updated_at
`

func (q *Queries) DeleteVirtualControl(ctx context.Context, topic string) (VirtualControl, error) {
	row := q.db.QueryRowContext(ctx, deleteVirtualControl, topic)
	var i VirtualControl
	err := row.Scan(
		&i.Topic,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVirtualControl = `-- name: GetVirtualControl :one
SELECT topic, value, created_at, updated_at
FROM virtual_controls
WHERE topic = ?
`

func (q *Queries) GetVirtualControl(ctx context.Context, topic string) (VirtualControl, error) {
	row := q.db.QueryRowContext(ctx, getVirtualControl, topic)
	var i VirtualControl
	err := row.Scan(
		&i.Topic,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVirtualControl = `-- name: UpdateVirtualControl :one
UPDATE virtual_controls
SET value      = ?,
    updated_at = datetime()
WHERE topic = ?
RETURNING topic, value, created_at, updated_at
`

type UpdateVirtualControlParams struct {
	Value string `json:"value"`
	Topic string `json:"topic"`
}

func (q *Queries) UpdateVirtualControl(ctx context.Context, arg UpdateVirtualControlParams) (VirtualControl, error) {
	row := q.db.QueryRowContext(ctx, updateVirtualControl, arg.Value, arg.Topic)
	var i VirtualControl
	err := row.Scan(
		&i.Topic,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
