name: Deploy docs site to Pages

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: docs/package-lock.json
          node-version: 22
          cache: npm

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Verify dependencies
        run: go mod verify

      - name: Run tests
        run: go test ./pkg/control/ && go test ./pkg/mqtt/ && go test ./internal/deploy/ && go test ./pkg/virualcontrol/

      - name: Run generate_docs.go
        run: go run scripts/generate_docs.go

      - name: Install dependencies
        working-directory: docs
        run: npm ci

      - name: Build with VitePress
        working-directory: docs
        run: npm run docs:build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4